### ISSUE TITLE
com.hazelcast.nio.serialization.HazelcastSerializationException

### ISSUE THREAD

**Issue by AlvaroSaez** [hazelcast/hazelcast-code-samples#32]
Hi, I trying to compile all the examples, but I find a problem, that I can't to solve.

In the example Cluster, that you have in "\hazelcast-code-samples\monitoring\cluster", when i'm trying to run ForceLocalMemberToBeSafe.java , Console show me this error:

Exception in thread "main" com.hazelcast.nio.serialization.HazelcastSerializationException: There is no suitable serializer for class ForceLocalMemberToBeSafe$MemberSafe
	at com.hazelcast.nio.serialization.SerializationServiceImpl.toData(SerializationServiceImpl.java:218)
	at com.hazelcast.nio.serialization.SerializationServiceImpl.toData(SerializationServiceImpl.java:203)
	at com.hazelcast.spi.impl.NodeEngineImpl.toData(NodeEngineImpl.java:180)
	at com.hazelcast.executor.impl.ExecutorServiceProxy.submitToMember(ExecutorServiceProxy.java:301)
	at com.hazelcast.executor.impl.ExecutorServiceProxy.submit(ExecutorServiceProxy.java:113)
	at ForceLocalMemberToBeSafe.main(ForceLocalMemberToBeSafe.java:50)
ene 15, 2015 6:02:28 PM com.hazelcast.util.HealthMonitor

 I don't know why I get this error

I use hazelcast 3.4 to complete your examples.

PS: IN other examples you use methods that are deprecated like 
         config.addAddress(); or config.getSocketOptions();
you can find this methods in client.java that you have in "\hazelcast-code-samples\clients\client-ssl\src\main\java"

**Comment by jerrinot** [comment]
Hi Alvaro,

thank you for reporting the issues. I have checked the ForceLocalMemberToBeSafe class and indeed there is a problem. MemberSafe class has to be serializable. I have wrote a trivial patch: https://github.com/hazelcast/hazelcast-code-samples/pull/33
