### ISSUE TITLE
Configure XML does not work anymore

### ISSUE THREAD

**Issue by manueljordan** [hazelcast/hazelcast-code-samples#454]
In two different Machines

* Windows 10
* Ubuntu 18.04

Through `STS` with the `m2` support (`Run Configurations`)

For `Learning Basics` with `mvn clean compile` all go well

```
[INFO] Reactor Summary for Learning Basics 0.1-SNAPSHOT:
[INFO] 
[INFO] Learning Basics .................................... SUCCESS [  0.297 s]
[INFO] Learning Basics - Logging Configuration ............ SUCCESS [  3.005 s]
[INFO] Learning Basics - Configure Programmatic ........... SUCCESS [  0.316 s]
[INFO] Learning Basics - Configure XML .................... SUCCESS [  0.376 s]
[INFO] Learning Basics - Configure YAML ................... SUCCESS [  0.380 s]
[INFO] Learning Basics - Destroying instances ............. SUCCESS [  0.426 s]
[INFO] Learning Basics - Loading instances ................ SUCCESS [  0.326 s]
[INFO] Learning Basics - Multiple Hazelcast Instances ..... SUCCESS [  0.285 s]
[INFO] Learning Basics - Unique Names ..................... SUCCESS [  0.304 s]
[INFO] Learning Basics - Wildcard Configuration ........... SUCCESS [  0.371 s]
[INFO] Learning Basics - Configuration of Data Structures at Runtime SUCCESS [  0.458 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  6.754 s
[INFO] Finished at: 2020-08-22T13:43:25-05:00
[INFO] ------------------------------------------------------------------------

```

But suddenly now to run the `Configure XML` sample:

```
Aug 22, 2020 1:44:33 PM com.hazelcast.internal.config.AbstractConfigLocator
INFO: Loading 'hazelcast.xml' from the classpath.
Aug 22, 2020 1:44:33 PM com.hazelcast.config.AbstractXmlConfigHelper
WARNING: Name of the hazelcast schema location[http://www.hazelcast.com/schema/config/hazelcast-config-4.0.xsd] is incorrect, using default
Aug 22, 2020 1:44:34 PM com.hazelcast.system
INFO: [192.168.1.16]:7000 [dev-configured-from-xml] [4.1-SNAPSHOT] Hazelcast 4.1-SNAPSHOT (20200821 - 8f550a9) starting at [192.168.1.16]:7000
Aug 22, 2020 1:44:34 PM com.hazelcast.instance.impl.Node
SEVERE: [192.168.1.16]:7000 [dev-configured-from-xml] [4.1-SNAPSHOT] Node creation failed
com.hazelcast.core.HazelcastException: java.lang.reflect.InvocationTargetException
	at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:627)
	at com.hazelcast.internal.util.ExceptionUtil.tryWrapInSameClass(ExceptionUtil.java:233)
	at com.hazelcast.internal.util.ExceptionUtil.wrapException(ExceptionUtil.java:138)
	at com.hazelcast.internal.util.ExceptionUtil.peel(ExceptionUtil.java:114)
	at com.hazelcast.internal.util.ExceptionUtil.peel(ExceptionUtil.java:73)
	at com.hazelcast.internal.util.ExceptionUtil.rethrow(ExceptionUtil.java:148)
	at com.hazelcast.instance.impl.DefaultNodeExtension.createSerializationService(DefaultNodeExtension.java:301)
	at com.hazelcast.instance.impl.Node.<init>(Node.java:249)
	at com.hazelcast.instance.impl.HazelcastInstanceImpl.createNode(HazelcastInstanceImpl.java:148)
	at com.hazelcast.instance.impl.HazelcastInstanceImpl.<init>(HazelcastInstanceImpl.java:117)
	at com.hazelcast.instance.impl.HazelcastInstanceFactory.constructHazelcastInstance(HazelcastInstanceFactory.java:211)
	at com.hazelcast.instance.impl.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:190)
	at com.hazelcast.instance.impl.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:128)
	at com.hazelcast.core.Hazelcast.newHazelcastInstance(Hazelcast.java:91)
	at Main.main(Main.java:31)
Caused by: com.hazelcast.core.HazelcastException: java.lang.reflect.InvocationTargetException
	at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:627)
	at com.hazelcast.internal.util.ExceptionUtil.tryWrapInSameClass(ExceptionUtil.java:233)
	at com.hazelcast.internal.util.ExceptionUtil.wrapException(ExceptionUtil.java:138)
	at com.hazelcast.internal.util.ExceptionUtil.peel(ExceptionUtil.java:114)
	at com.hazelcast.internal.util.ExceptionUtil.peel(ExceptionUtil.java:73)
	at com.hazelcast.internal.util.ExceptionUtil.rethrow(ExceptionUtil.java:148)
	at com.hazelcast.internal.serialization.impl.SerializerHookLoader.load(SerializerHookLoader.java:69)
	at com.hazelcast.internal.serialization.impl.SerializerHookLoader.<init>(SerializerHookLoader.java:55)
	at com.hazelcast.internal.serialization.impl.DefaultSerializationServiceBuilder.registerSerializerHooks(DefaultSerializationServiceBuilder.java:310)
	at com.hazelcast.internal.serialization.impl.DefaultSerializationServiceBuilder.build(DefaultSerializationServiceBuilder.java:238)
	at com.hazelcast.internal.serialization.impl.DefaultSerializationServiceBuilder.build(DefaultSerializationServiceBuilder.java:55)
	at com.hazelcast.instance.impl.DefaultNodeExtension.createSerializationService(DefaultNodeExtension.java:299)
	... 8 more
Caused by: com.hazelcast.core.HazelcastException: java.lang.reflect.InvocationTargetException
	at com.hazelcast.internal.util.ServiceLoader$NewInstanceIterator.next(ServiceLoader.java:304)
	at com.hazelcast.internal.serialization.impl.SerializerHookLoader.load(SerializerHookLoader.java:62)
	... 13 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.hazelcast.internal.util.ServiceLoader$NewInstanceIterator.next(ServiceLoader.java:296)
	... 14 more
Caused by: java.lang.NoClassDefFoundError: org/hibernate/cache/spi/entry/CacheEntry
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:757)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
	at com.hazelcast.hibernate.serialization.Hibernate5CacheEntrySerializerHook.<init>(Hibernate5CacheEntrySerializerHook.java:27)
	... 19 more
Caused by: java.lang.ClassNotFoundException: org.hibernate.cache.spi.entry.CacheEntry
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
	... 32 more

Aug 22, 2020 1:44:34 PM com.hazelcast.instance.impl.NodeExtension
INFO: [192.168.1.16]:7000 [dev-configured-from-xml] [4.1-SNAPSHOT] Destroying node NodeExtension.
Exception in thread "main" com.hazelcast.core.HazelcastException: java.lang.reflect.InvocationTargetException
	at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:627)
	at com.hazelcast.internal.util.ExceptionUtil.tryWrapInSameClass(ExceptionUtil.java:233)
	at com.hazelcast.internal.util.ExceptionUtil.wrapException(ExceptionUtil.java:138)
	at com.hazelcast.internal.util.ExceptionUtil.peel(ExceptionUtil.java:114)
	at com.hazelcast.internal.util.ExceptionUtil.peel(ExceptionUtil.java:73)
	at com.hazelcast.internal.util.ExceptionUtil.rethrow(ExceptionUtil.java:148)
	at com.hazelcast.instance.impl.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:194)
	at com.hazelcast.instance.impl.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:128)
	at com.hazelcast.core.Hazelcast.newHazelcastInstance(Hazelcast.java:91)
	at Main.main(Main.java:31)
Caused by: com.hazelcast.core.HazelcastException: java.lang.reflect.InvocationTargetException
	at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:627)
	at com.hazelcast.internal.util.ExceptionUtil.tryWrapInSameClass(ExceptionUtil.java:233)
	at com.hazelcast.internal.util.ExceptionUtil.wrapException(ExceptionUtil.java:138)
	at com.hazelcast.internal.util.ExceptionUtil.peel(ExceptionUtil.java:114)
	at com.hazelcast.internal.util.ExceptionUtil.peel(ExceptionUtil.java:73)
	at com.hazelcast.internal.util.ExceptionUtil.rethrow(ExceptionUtil.java:148)
	at com.hazelcast.instance.impl.HazelcastInstanceFactory.constructHazelcastInstance(HazelcastInstanceFactory.java:237)
	at com.hazelcast.instance.impl.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:190)
	... 3 more
Caused by: com.hazelcast.core.HazelcastException: java.lang.reflect.InvocationTargetException
	at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:627)
	at com.hazelcast.internal.util.ExceptionUtil.tryWrapInSameClass(ExceptionUtil.java:233)
	at com.hazelcast.internal.util.ExceptionUtil.wrapException(ExceptionUtil.java:138)
	at com.hazelcast.internal.util.ExceptionUtil.peel(ExceptionUtil.java:114)
	at com.hazelcast.internal.util.ExceptionUtil.peel(ExceptionUtil.java:73)
	at com.hazelcast.internal.util.ExceptionUtil.rethrow(ExceptionUtil.java:148)
	at com.hazelcast.instance.impl.Node.<init>(Node.java:287)
	at com.hazelcast.instance.impl.HazelcastInstanceImpl.createNode(HazelcastInstanceImpl.java:148)
	at com.hazelcast.instance.impl.HazelcastInstanceImpl.<init>(HazelcastInstanceImpl.java:117)
	at com.hazelcast.instance.impl.HazelcastInstanceFactory.constructHazelcastInstance(HazelcastInstanceFactory.java:211)
	... 4 more
Caused by: com.hazelcast.core.HazelcastException: java.lang.reflect.InvocationTargetException
	at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:627)
	at com.hazelcast.internal.util.ExceptionUtil.tryWrapInSameClass(ExceptionUtil.java:233)
	at com.hazelcast.internal.util.ExceptionUtil.wrapException(ExceptionUtil.java:138)
	at com.hazelcast.internal.util.ExceptionUtil.peel(ExceptionUtil.java:114)
	at com.hazelcast.internal.util.ExceptionUtil.peel(ExceptionUtil.java:73)
	at com.hazelcast.internal.util.ExceptionUtil.rethrow(ExceptionUtil.java:148)
	at com.hazelcast.instance.impl.DefaultNodeExtension.createSerializationService(DefaultNodeExtension.java:301)
	at com.hazelcast.instance.impl.Node.<init>(Node.java:249)
	... 7 more
Caused by: com.hazelcast.core.HazelcastException: java.lang.reflect.InvocationTargetException
	at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:627)
	at com.hazelcast.internal.util.ExceptionUtil.tryWrapInSameClass(ExceptionUtil.java:233)
	at com.hazelcast.internal.util.ExceptionUtil.wrapException(ExceptionUtil.java:138)
	at com.hazelcast.internal.util.ExceptionUtil.peel(ExceptionUtil.java:114)
	at com.hazelcast.internal.util.ExceptionUtil.peel(ExceptionUtil.java:73)
	at com.hazelcast.internal.util.ExceptionUtil.rethrow(ExceptionUtil.java:148)
	at com.hazelcast.internal.serialization.impl.SerializerHookLoader.load(SerializerHookLoader.java:69)
	at com.hazelcast.internal.serialization.impl.SerializerHookLoader.<init>(SerializerHookLoader.java:55)
	at com.hazelcast.internal.serialization.impl.DefaultSerializationServiceBuilder.registerSerializerHooks(DefaultSerializationServiceBuilder.java:310)
	at com.hazelcast.internal.serialization.impl.DefaultSerializationServiceBuilder.build(DefaultSerializationServiceBuilder.java:238)
	at com.hazelcast.internal.serialization.impl.DefaultSerializationServiceBuilder.build(DefaultSerializationServiceBuilder.java:55)
	at com.hazelcast.instance.impl.DefaultNodeExtension.createSerializationService(DefaultNodeExtension.java:299)
	... 8 more
Caused by: com.hazelcast.core.HazelcastException: java.lang.reflect.InvocationTargetException
	at com.hazelcast.internal.util.ServiceLoader$NewInstanceIterator.next(ServiceLoader.java:304)
	at com.hazelcast.internal.serialization.impl.SerializerHookLoader.load(SerializerHookLoader.java:62)
	... 13 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.hazelcast.internal.util.ServiceLoader$NewInstanceIterator.next(ServiceLoader.java:296)
	... 14 more
Caused by: java.lang.NoClassDefFoundError: org/hibernate/cache/spi/entry/CacheEntry
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:757)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
	at com.hazelcast.hibernate.serialization.Hibernate5CacheEntrySerializerHook.<init>(Hibernate5CacheEntrySerializerHook.java:27)
	... 19 more
Caused by: java.lang.ClassNotFoundException: org.hibernate.cache.spi.entry.CacheEntry
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
	... 32 more
```
**Observation:** in Windows 10 I deleted the Maven repository, therefore Maven again got all the dependencies and sadly persists this situation. It happens in the 2 different machines

What is wrong?

**Comment by mmedenjak** [comment]
I believe this has been fixed recently (https://github.com/hazelcast/hazelcast-hibernate/pull/212) so maybe you can give it a new try with the latest commits. If it still doesn't work, @pivovarit may be able to help.

**Comment by pivovarit** [comment]
Yes, that is fixed in Hibernate master, but it will be truly fixed once the artifact gets included in hazelcast-all, which should be today/tomorrow

**Comment by pivovarit** [comment]
Confirmed that got fixed in the newest SNAPSHOT>

**Comment by manueljordan** [comment]
Thanks so much, because I am with this situation since last Friday and I did do in each machine `git fetch upstream` and `git merge upstream/master` ... thank you
